name: CI

on:
  push:
    branches:
    - main
    paths:
    - '_build_flag'
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:

#Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
#Checkout code from repository
    - name: Checkout Code
      uses: actions/checkout@v1 
      
#Set EnvironmSet Environment Variables
    - name: "Set environment variables"
      run: |
          echo "CG_TOKEN=${{ secrets.CG_TOKEN }}" >> $GITHUB_ENV 
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV 
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV 
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV 
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV 
          
#Install Dependencies      
    - name: Install Relevant Plugins + Dependencies
      run: |
          npm install -g serverless 
          npm i --save serverless-azure-functions
          npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          
#Deploy Function
    - name: Intial Deploy to Azure
      run: |
         cloudguard fsp add -p azure -r python -s ${AZURE_SUBSCRIPTION_ID} -i src\handlers\ -t ${CG_TOKEN}
         sls deploy
      timeout-minutes: 30   
