name: 'Destroy'
on:
  push:
    branches:
    - main
    paths:
    - '_destroy_flag'

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: .
      CG_TOKEN: ${{ secrets.CG_TOKEN }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZ_RG: ${{ secrets.AZ_RG }}
      AZ_LOCATION: ${{ secrets.AZ_LOCATION }}
      STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      AZURE_FUNCTIONAPP_NAME: ${{ secrets.APP_NAME }}
      AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
         
    steps:

#Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
#Checkout code from repository
    - name: Checkout Code
      uses: actions/checkout@v1 
       
#Destroy Env     
    - name: Install Relevant Plugins + Dependencies
      run: |

        location_lower=$(echo "${AZ_LOCATION}" | awk '{print tolower($0)}')
        location_lower="$(echo -e "$location_lower" | tr -d '[:space:]')"
       
        az login  --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} -t ${AZURE_TENANT_ID}
        az functionapp delete --resource-group ${AZ_RG}  --name ${APP_NAME} --yes
        az storage account delete --name ${STORAGE_NAME}  --resource-group ${AZ_RG} --yes
        az group delete --name ${AZ_RG} --yes
         


    
